#!mainFile "main.opy"

settings {
    "main": {
        "description": "Here we go again.\n\nWelcome To Legal Cheats V2!\n\nThis is the new and improved version, new changes, new bugs!\nPressing Interact Starts the cheats and if they dont do anything there probably something else like there ability\n\n•Original Version : KDJCN\n•Old Hard Edition:  XMG2D\n•Current Hard Edition: nan\n\nlearn more at workshop.codes/legalhacksgain\nif you like source code heres it is: https://github.com/Astridisweird/legalcheats2.0",
        "modeName": "LEGAL CHEATS V2"
    },
    "lobby": {
        "allowPlayersInQueue": true,
        "mapRotation": "afterGame",
        "enableMatchVoiceChat": true,
        "returnToLobby": "never"
    },
    "gamemodes": {
        "control": {
            "enableCompetitiveRules": true
        },
        "escort": {
            "enableCompetitiveRules": true
        },
        "flashpoint": {
            "enableCompetitiveRules": true
        },
        "hybrid": {
            "enableCompetitiveRules": true
        },
        "push": {
            "enableCompetitiveRules": true
        },
        "general": {
            "gamemodeStartTrigger": "immediately",
            "roleLimit": "1Tank2Offense2Support"
        }
    },
    "heroes": {
        "allTeams": {
            "echo": {
                "enableAbility1": false
            },
            "lifeweaver": {
                "enableAbility2": false
            }
        }
    }
}

#Activated extensions

#!extension beamEffects
#!extension projectiles